- src/ThreeEditor/js/Viewport.js
- src/ThreeEditor/js/ViewportManager.js
> comments and refactoring

- src/ThreeEditor/ThreeEditor.tsx
- src/ThreeEditor/js/Editor.js
- src/ThreeEditor/main.js
- src/ThreeEditor/util/CSGManager.ts
- src/components/ZoneManagerPanel/BooleanAlgebraRow.tsx
- src/components/ZoneManagerPanel/ZoneManagerPanel.tsx
- src/util/parseZone/parseZone.ts
Add to the existing layer of persistency state of the CSGManager.
Remember to wait until DB saves state.
Example log:
Closes #72.
> add CSGManager to editor persistency in IndexedDB (#72)

- package-lock.json
- package.json
- src/ThreeEditor/js/Editor.js
- src/ThreeEditor/js/Sidebar.Geometry.BoxGeometry.js
- src/ThreeEditor/js/Sidebar.Geometry.CylinderGeometry.js
- src/ThreeEditor/js/Sidebar.Geometry.SphereGeometry.js
- src/ThreeEditor/js/Sidebar.Object.js
- src/ThreeEditor/js/Viewport.ClipPlane.js
- yarn.lock
> Add units and fix radius (#91) (#93)

- src/ThreeEditor/js/Sidebar.Geometry.BoxGeometry.js
- src/ThreeEditor/util/AdditionalUserData.ts
> restore params (#184)

- package.json
- src/JsRoot/JsRootGraph.tsx
- src/WrapperApp/WrapperApp.tsx
- src/WrapperApp/components/ResultsPanel.tsx
- src/WrapperApp/components/TabPanel.tsx
> fix demo and results rendering (#236)

- .github/workflows/node.js.yml
- dockerRun.ps1
> deploy app on remote (#256)

- src/ThreeEditor/components/MaterialSelect/MaterialSelect.tsx
- src/ThreeEditor/js/Editor.js
- src/ThreeEditor/js/Sidebar.Material.ZoneMaterial.js
- src/ThreeEditor/util/BoundingZone.ts
- src/ThreeEditor/util/Materials/MaterialsManager.ts
- src/ThreeEditor/util/Materials/SimulationMaterial.ts
- src/ThreeEditor/util/Materials/materials.ts
- src/ThreeEditor/util/UiUtils.js
> add search select (#114)

- src/ThreeEditor/js/Editor.js
- src/ThreeEditor/js/Menubar.Add.js
- src/ThreeEditor/js/Sidebar.Geometry.WorldZone.js
- src/ThreeEditor/js/Sidebar.Geometry.js
- src/ThreeEditor/js/Sidebar.Object.js
- src/ThreeEditor/js/Sidebar.Scene.js
- src/ThreeEditor/js/Viewport.js
- src/ThreeEditor/js/ViewportObjects.ts
- src/ThreeEditor/util/BasicMeshes.ts
- src/ThreeEditor/util/CSG/CSGZoneManager.ts
- src/ThreeEditor/util/ObjectLoader.ts
- src/ThreeEditor/util/SimulationObject.ts
- src/ThreeEditor/util/WorldZone.ts
> block rotation, add custom meshes and loader (#183)

- src/ThreeEditor/util/AdditionalUserData.ts
- src/ThreeEditor/util/WorldZone.ts
> add userdata(#287)

- src/WrapperApp/WrapperApp.tsx
- src/services/AuthService.tsx
> disable auth on demo (#296)

- src/ThreeEditor/js/viewport/Viewport.ClipPlane.js
- src/ThreeEditor/js/viewport/Viewport.js
- src/ThreeEditor/util/Beam.ts
- src/ThreeEditor/util/CSG/CSGZone.ts
- src/ThreeEditor/util/Detect/DetectManager.ts
- src/ThreeEditor/util/WorldZone.ts
> fix loading project and cacel debounce (#302)

- src/ThreeEditor/js/Editor.js
- src/ThreeEditor/js/Loader.js
- src/ThreeEditor/main.js
> add version prompt and bump JSON to 0.2 (#185)

- src/ThreeEditor/css/main.css
- src/ThreeEditor/js/sidebar/Sidebar.OutlinerManager.js
- src/ThreeEditor/util/Detect/DetectFilter.ts
- src/ThreeEditor/util/Detect/DetectManager.ts
- src/ThreeEditor/util/SimulationBase/SimulationObject.ts
- src/ThreeEditor/util/WorldZone.ts
> add visibility checkbox (#210)

- src/ThreeEditor/js/sidebar/object/Object.Material.ts
- src/ThreeEditor/util/Detect/DetectRule.ts
- src/ThreeEditor/util/Detect/DetectRuleTypes.ts
- src/ThreeEditor/util/Scoring/ScoringOutput.ts
> Fix detect color error

- src/ThreeEditor/js/Editor.js
- src/ThreeEditor/js/menubar/Menubar.File.js
> move updating UserData to toJson (#334)

- public/index.html
- src/WrapperApp/components/LoginPanel.tsx
- src/WrapperApp/components/Simulation/SimulationStatus.tsx
- src/services/ShSimulationService.tsx
Add the 'Show Details' button to the error state of the simulation.
> add error info

- .github/workflows/node.js.yml
- buildPython.js
this should stop action after first error
> improve ssh-action script

- package-lock.json
- package.json
- src/WrapperApp/components/ResultsPanel.tsx
> Update graph background on dark mode

- src/ThreeEditor/examples/ex2.json
Adjusted title, bodies names, zone names and camera view.
> Adjust simple example

- buildPython.js
> fix deploy (#481)

- src/ThreeEditor/css/main.css
- src/ThreeEditor/js/Editor.js
- src/ThreeEditor/js/menubar/Menubar.Examples.js
- src/ThreeEditor/js/menubar/Menubar.File.js
- src/ThreeEditor/js/menubar/Menubar.Settings.History.js
- src/ThreeEditor/js/menubar/Menubar.Settings.Shortcuts.js
- src/ThreeEditor/js/menubar/Menubar.Settings.Viewport.js
- src/ThreeEditor/js/menubar/Menubar.Settings.js
- src/ThreeEditor/js/sidebar/Sidebar.Project.js
- src/ThreeEditor/js/sidebar/Sidebar.js
- src/ThreeEditor/main.js
> move settings to menu (#473) and add project description (#474)

- src/JsRoot/JsRootGraph1D.tsx
- src/JsRoot/JsRootGraph2D.tsx
> improve plotting

- package-lock.json
- package.json
- src/JsRoot/JsRootGraph1D.tsx
- src/JsRoot/JsRootGraph2D.tsx
- src/WrapperApp/components/ResultsPanel.tsx
> add resize and bigger graph

- src/PythonConverter/PythonConverterService.tsx
- src/WrapperApp/components/InputEditor/InputEditorPanel.tsx
> Fix Pyodide loading

- src/ThreeEditor/components/Sidebar/EditorSidebar.tsx
- src/ThreeEditor/js/Editor.Context.ts
- src/ThreeEditor/js/Editor.js
- src/ThreeEditor/js/sidebar/Sidebar.js
> Move detector context

- src/WrapperApp/components/InputEditor/InputFilesEditor.tsx
> disable button on empty file

- src/services/ShSimulatorService.tsx
Now works with
https://github.com/yaptide/yaptide/pull/241
> Integrate new rest API

- src/ThreeEditor/examples/examples.ts
- src/util/Sort.ts
> examples appear again (#789)

- src/WrapperApp/components/InputEditor/InputFilesEditor.tsx
> add scroll (#751)

- src/ThreeEditor/components/Sidebar/propeteries/category/ObjectMaterial.tsx
> rename material tab (#480)

- .gitignore
- src/ThreeEditor/examples/ex1.json
- src/ThreeEditor/examples/ex2.json
- src/ThreeEditor/examples/ex3.json
- src/ThreeEditor/js/EditorJson.ts
- src/WrapperApp/WrapperApp.tsx
- src/WrapperApp/components/Simulation/SimulationPanel.tsx
- src/WrapperApp/components/Simulation/SimulationProgressBar.tsx
- src/WrapperApp/components/Simulation/SimulationStatus.tsx
- src/services/AuthService.tsx
- src/services/DataLoaderService.tsx
- src/services/RequestTypes.ts
- src/services/ResponseTypes.ts
- src/services/ShSimulatorService.tsx
- src/services/TypeTransformUtil.tsx
> Add new progress bars for running simulation

- src/ThreeEditor/ThreeEditor.tsx
- src/WrapperApp/components/InputEditor/InputEditorPanel.tsx
- src/WrapperApp/components/Results/ResultsPanel.tsx
- src/WrapperApp/components/Simulation/SimulationPanel.tsx
- src/services/RequestTypes.ts
goes in pair with [#264](https://github.com/yaptide/yaptide/pull/264)
> Reformat input files and fix appbar error

- buildPython.js
Use method from path module to get file name
> Fix extraction of filename

- src/ThreeEditor/components/EditorAppBar/EditorAppBar.tsx
- src/WrapperApp/WrapperApp.tsx
- src/WrapperApp/components/InputEditor/InputEditorPanel.tsx
- src/WrapperApp/components/InputEditor/InputFilesEditor.tsx
- src/WrapperApp/components/Simulation/RunSimulationForm.tsx
- src/WrapperApp/components/Simulation/SimulationPanel.tsx
Results data provided through the URL should stay there until you remove it. 
Running the simulation with input files opens up the config panel
> Fix #935 and #901

- src/ThreeEditor/js/viewport/Viewport.ClippedViewCSG.ts
- src/ThreeEditor/js/viewport/Viewport.js
> Add helpers to cross-sections

- .github/workflows/manual_deploy.yml
- .github/workflows/manual_test.yml
- .github/workflows/node.js.yml
This PR modifies permissions for dependabot so it will be able to push docker images to Github Package Registry.
Moreover several fixes are added to manual workflows.
The yaml files are reformatted as well
> fix GitHub actions for dependabot

- .github/workflows/manual_deploy.yml
- .github/workflows/node.js.yml
- Dockerfile
This PR follows https://github.com/yaptide/ui/pull/1050 and adjusts properly the Dockerfile and script which builds the image for docker container registry
> adjust Dockerfile for new type of development

- src/WrapperApp/components/Simulation/SimulationPanel.tsx
Adjustment of UI to cope with better paging schema on backend, as being implemented in https://github.com/yaptide/yaptide/pull/446
> improved paging

- .github/workflows/manual_test.yml
- buildPython.js
Manual tests are failing being stucked to 6 hours:
> cross-platform build for python

- Dockerfile
- docker-compose.yml
- nginx.conf
This is needed to get working key cloak integration, see https://github.com/yaptide/ui/pull/1086
> 1095 add https support

- src/ThreeEditor/js/viewport/ViewportManager.js
> Set setPixelRatio to 1

- src/ThreeEditor/Simulation/Base/SimulationContainer.ts
- src/ThreeEditor/Simulation/Base/SimulationManager.ts
- src/ThreeEditor/Simulation/Detectors/Detector.ts
- src/ThreeEditor/Simulation/Detectors/DetectorManager.ts
- src/ThreeEditor/Simulation/Figures/FigureManager.ts
- src/ThreeEditor/Simulation/Scoring/ScoringManager.ts
- src/ThreeEditor/Simulation/Scoring/ScoringOutput.ts
- src/ThreeEditor/Simulation/Zones/ZoneManager.ts
- src/ThreeEditor/components/Dialog/RunSimulationDialog.tsx
- src/ThreeEditor/components/Sidebar/EditorSidebar.tsx
- src/ThreeEditor/components/Sidebar/SidebarTree/SidebarTree.tsx
- src/ThreeEditor/components/Sidebar/SidebarTree/SidebarTreeItem.tsx
- src/ThreeEditor/components/Sidebar/properties/category/ObjectPlacement.tsx
- src/ThreeEditor/components/ZoneManagerPanel/ZoneManagerPanel.tsx
- src/ThreeEditor/js/commands/SetDetectPositionCommand.js
- src/ThreeEditor/js/commands/SetDetectTypeCommand.js
- src/ThreeEditor/js/commands/SetMaterialColorCommand.js
- src/ThreeEditor/js/commands/SetValueCommand.js
- src/ThreeEditor/js/viewport/Viewport.js
- src/WrapperApp/components/InputEditor/InputFilesEditor.tsx
- src/util/Name/Name.ts
- src/util/Ui/CommandButtonProps.ts
- src/util/hooks/useKeyboardEditorControls.ts
various command execute and undo interactions were tested and fixed
> Fix command stability

- src/WrapperApp/components/Simulation/SimulationCard.tsx
- src/WrapperApp/components/Simulation/SimulationCardGrid.tsx
- src/WrapperApp/components/Simulation/SimulationPanel.tsx
- src/services/AuthService.tsx
- src/services/ShSimulatorService.tsx
> Job status refresh button

- src/ThreeEditor/components/Dialog/SaveFileDialog.tsx
- src/WrapperApp/components/Simulation/SimulationCard.tsx
- src/WrapperApp/components/Simulation/SimulationPanel.tsx
- src/services/ShSimulatorService.tsx
- src/types/ResponseTypes.ts
> 220 resolve cancel issues

- src/ThreeEditor/components/Dialog/SaveFileDialog.tsx
- src/WrapperApp/components/Results/ResultsPanel.tsx
- src/WrapperApp/components/Simulation/SimulationCard.tsx
- src/types/ResponseTypes.ts
> Fix button functionality on simulation card

- src/services/AuthService.tsx
> display all errors sent as response.

- src/WrapperApp/components/Simulation/RunSimulationForm.tsx
Add simulator selection before run
Resolves #1287
> Resolves 1287 Enable fluka simulation selection

- src/WrapperApp/components/NavDrawer/NavDrawerList.tsx
| ![image](https://github.com/yaptide/ui/assets/26445545/0a9bd945-e10a-450c-a15f-679d97482175) | ![image](https://github.com/yaptide/ui/assets/26445545/5c31fcd9-2c11-43a6-bd1a-0f7568b86945) |
| - | - |
> Add documentation button

- nginx.conf
This PR makes Qualsys SSL test happy:
> nginx configuration improved

- src/WrapperApp/components/Simulation/BatchParametersEditor.tsx
These are most commonly used options, adding them simplifies to deal with problems in https://github.com/yaptide/yaptide/issues/687
Tested on yap-dev machine, seems to work
> more options for sbatch

- src/JsRoot/GraphData.tsx
- src/ThreeEditor/Simulation/Detectors/DetectorManager.ts
- src/ThreeEditor/Simulation/Figures/FigureManager.ts
- src/ThreeEditor/Simulation/Materials/MaterialManager.ts
- src/ThreeEditor/Simulation/Scoring/CustomFilter.ts
- src/ThreeEditor/Simulation/Scoring/ParticleFilter.ts
- src/ThreeEditor/Simulation/Scoring/ScoringFilter.ts
- src/ThreeEditor/Simulation/Scoring/ScoringManager.ts
- src/ThreeEditor/Simulation/SpecialComponents/SpecialComponentManager.ts
- src/ThreeEditor/Simulation/Zones/ZoneManager.ts
- src/ThreeEditor/components/Sidebar/properties/PropertiesPanel.tsx
- src/ThreeEditor/components/Sidebar/properties/category/CustomFilterConfiguration.tsx
- src/ThreeEditor/components/Sidebar/properties/category/ParticleFilterConfiguration.tsx
- src/ThreeEditor/examples/ex1.json
- src/ThreeEditor/examples/migrations/migrateEx0.10_0.11.js
- src/ThreeEditor/js/EditorContext.ts
- src/ThreeEditor/js/YaptideEditor.js
- src/ThreeEditor/js/commands/DuplicateObjectCommand.ts
- src/ThreeEditor/js/sidebar/object/Object.Filter.ts
- src/WrapperApp/components/Results/ResultsTable.tsx
- src/util/Ui/CommandButtonProps.ts
- src/util/hooks/useKeyboardEditorControls.ts
> 1400 define particle filter

- package-lock.json
- package.json
Fixed by running: 
```
PS C:\Users\Legion\workspace\ui> npx update-browserslist-db@latest
Need to install the following packages:
update-browserslist-db@1.0.13
Ok to proceed? (y) y
Latest version:     1.0.30001605
Installed version:  1.0.30001533
Removing old caniuse-lite from lock file
Installing new caniuse-lite version
$ npm install caniuse-lite
Cleaning package.json dependencies from caniuse-lite
$ npm uninstall caniuse-lite
caniuse-lite has been successfully updated
No target browser changes
```
> update browser lists

- src/JsRoot/components/JsRootGraph1D.tsx
- src/JsRoot/hook/useJsRootCanvas.tsx
> plots improvements

- src/WrapperApp/components/Simulation/BackendSimulations/BackendSimulations.tsx
- src/WrapperApp/components/Simulation/RunSimulationForm.tsx
- src/WrapperApp/components/Simulation/SimulationCardGrid.tsx
- src/WrapperApp/components/Simulation/SimulationPanel.tsx
- src/types/RequestTypes.ts
Fixes #1601 
This pull request includes several changes aimed at enhancing the simulation components by introducing a new `SimulatorType` and `SimulatorNames` mapping, and updating various components to utilize these new types.
Key changes include:
* `src/WrapperApp/components/Simulation/BackendSimulations/BackendSimulations.tsx`:
- Added `SimulatorType` import and included `simulator` in `BackendSimulationsProps` and component props. [[1]](diffhunk://#diff-b3bd6222cf0d4820a1038c2d52bae812bbc23a5f82984ef02498bb5172a2d35dR6) [[2]](diffhunk://#diff-b3bd6222cf0d4820a1038c2d52bae812bbc23a5f82984ef02498bb5172a2d35dR24) [[3]](diffhunk://#diff-b3bd6222cf0d4820a1038c2d52bae812bbc23a5f82984ef02498bb5172a2d35dR120)
* `src/WrapperApp/components/Simulation/RunSimulationForm.tsx`:
- Added …
> Fix simulator exclusion between project and simulation window Issue: #1601
