package-lock.json
package.json
src/ThreeEditor/js/Editor.js
src/ThreeEditor/js/Loader.js
src/ThreeEditor/js/Menubar.File.js
yarn.lock

Added possibility to export state of the editor to a file and import state from a file.
Closes #60.

add import-export editor file (#60)

---

src/ThreeEditor/ThreeEditor.tsx
src/ThreeEditor/js/Editor.js
src/ThreeEditor/js/Sidebar.Settings.Shortcuts.js
src/ThreeEditor/js/Viewport.js
src/ThreeEditor/main.js
src/WrapperApp/WrapperApp.tsx

add focus to editor container (#227)

---

src/ThreeEditor/js/EditorOrbitControls.js
src/ThreeEditor/js/LoaderUtils.js
src/ThreeEditor/js/Menubar.Add.js
src/ThreeEditor/js/Menubar.Edit.js
src/ThreeEditor/js/Menubar.File.js
src/ThreeEditor/js/Menubar.Help.js
src/ThreeEditor/js/Menubar.Layout.js
src/ThreeEditor/js/Menubar.View.js
src/ThreeEditor/js/Menubar.js
src/ThreeEditor/js/Sidebar.Geometry.Beam.js
src/ThreeEditor/js/Sidebar.Geometry.BoundingZone.js
src/ThreeEditor/js/Sidebar.Geometry.BoxGeometry.js
src/ThreeEditor/js/Sidebar.Geometry.CylinderGeometry.js
src/ThreeEditor/js/Sidebar.Geometry.SphereGeometry.js
src/ThreeEditor/js/Sidebar.Geometry.js
src/ThreeEditor/js/Sidebar.Object.js
src/ThreeEditor/js/Sidebar.Project.Renderer.js
src/ThreeEditor/js/Sidebar.Project.js
src/ThreeEditor/js/Sidebar.Scene.js
src/ThreeEditor/js/Sidebar.Settings.History.js
src/ThreeEditor/js/Sidebar.Settings.Shortcuts.js
src/ThreeEditor/js/Sidebar.Settings.js
src/ThreeEditor/js/Storage.js
src/ThreeEditor/js/Viewport.Camera.js
src/ThreeEditor/js/Viewport.js
src/ThreeEditor/util/UiUtils.js
src/WrapperApp/WrapperApp.tsx

161 cleanup UI creation

---

src/ThreeEditor/components/Sidebar/propeteries/category/ObjectInfo.tsx
src/ThreeEditor/components/Sidebar/propeteries/category/PropertiesCategory.tsx
src/ThreeEditor/components/Sidebar/tabs/EditorSidebarTabTree.tsx

hide beam info and make accordion square (#479)

---

buildPython.js

It seems that upgrading glob done in https://github.com/yaptide/ui/pull/827 broke out github pages deploy.
Current version of `glob` seems to return Promise by default. Therefore simplifying the code could fix the issue with not working converter on demo version

fixing github pages deploy

---

src/ThreeEditor/components/Sidebar/propeteries/category/BeamConfiguration.tsx
src/ThreeEditor/util/Beam.ts

Adds additional optional parameter BEAMSAD

Add sad parameter #753

---

.github/workflows/dependabot.yml

Right now to merge dependabot PRs we need to do following steps:
- mark the PR as "Ready to be merged"
- test manually the PR
- give it approve
After this PR first step won't be necessary, following workflow should work:
- test manually the PR
- give it approve

Automatically mark dependabot PRs as ready to merge

---

.github/workflows/node.js.yml
package-lock.json
package.json
src/WrapperApp/components/NavDrawer/NavDrawer.test.ts

just to check if selenium test will work with github actions

basic selenium test for menu button

---

src/ThreeEditor/Simulation/Materials/MaterialManager.ts
src/ThreeEditor/Simulation/Materials/SimulationMaterial.ts
src/ThreeEditor/components/Sidebar/EditorSidebar.tsx
src/ThreeEditor/components/Sidebar/SidebarTree/SidebarTree.style.css
src/ThreeEditor/components/Sidebar/SidebarTree/SidebarTree.tsx
src/ThreeEditor/components/Sidebar/SidebarTree/SidebarTreeItem.tsx
src/ThreeEditor/components/Sidebar/tabs/EditorSidebarTabTree.tsx
src/ThreeEditor/js/commands/ChangeObjectOrderCommand.ts
src/util/CounterMap/CounterMap.ts

Close #987
Close #997
Close #967

Add multiple reorders

---

src/config/Config.ts
src/services/AuthService.tsx

Run with env variable `REACT_APP_DEPLOYMENT=dev`: 
`npx cross-env REACT_APP_DEPLOYMENT=dev npm run start`
Paste in the console to change URL
`
BACKEND_URL = "http://amogus:8000" 
`

Add configurable backend URL

---

.github/workflows/manual_test.yml
.github/workflows/node.js.yml
Dockerfile
README.md
buildPython.js
src/WrapperApp/components/Simulation/SimulationPanel.tsx

It seems that recently a `node:18` docker image got an upgrade of Python version from 3.10 to 3.11.
In the main dockerfile we've been using pip to install some packages needed to build and install converter pip package.
In 3.10 it was still possible to install packages via pip system-wide.
New python version 3.11 gives an error when user wants to install package via pip system-wide and forces users to use venv.
This PR adjusts the preparation of the converter package to use venv as well.
The change is necessary to have properly working deploy process.

building process adapted to the python 3.11

---

.github/workflows/manual_test.yml
buildPython.js

Running `npm run start` failed for me with the following error. I am using Windows and Python 3.12. This change fixed the issue

Install setuptools

---

src/ThreeEditor/Simulation/Physics/Beam.ts
src/ThreeEditor/components/Sidebar/properties/category/BeamConfiguration.tsx
src/ThreeEditor/js/sidebar/object/Object.Beam.ts

send particle name along with id to backend. Reason is to add particle name to comment in shieldhit input file (see linked issue)

add particle name to json

---

public/index.html

Remove noscript section, as required by WCAG

Remove noscript

---

Dockerfile
buildPython.js
src/PythonConverter/PythonWorker.ts

Related to PR in converter module: https://github.com/yaptide/converter/pull/191
The mentioned PR should be resolved and merged before merging this one.
Then, the git submodule in this MR should be updated.

Install converter with poetry

---

README.md

Developing yaptide using docker - important note about setting REACT_APP_BACKEND_URL.

Readme update. Developing yaptide with docker

---

src/WrapperApp/components/Results/EstimatorsSelect/EstimatorsSelect.tsx
src/WrapperApp/components/Results/ResultsPanel.tsx
src/services/ShSimulatorService.tsx

PR needed by https://github.com/yaptide/yaptide/pull/1243
This pull request includes several changes to the `src/WrapperApp/components/Results` and `src/services/ShSimulatorService.tsx` files to improve the handling of estimator names and refactoring of the code. The most important changes include removing the trailing underscore from estimator names, simplifying the `ResultsPanel` component, and refactoring the `ShSimulatorService` to remove unused functions.
Changes to estimator names:
* [`src/WrapperApp/components/Results/EstimatorsSelect/EstimatorsSelect.tsx`](diffhunk://#diff-86366529814e7f6c49e009e561f2d2d2d7056fe18857c39dcf3b822e863f5294L37-R37): Removed the trailing underscore from the `estimatorName` in the `getJobResult` call.
* …

Ui changes for adjusted estimator db model

---

src/services/ShSimulatorService.tsx

This pull request includes changes to the `src/services/ShSimulatorService.tsx` file to introduce a new function for updating estimator references and integrate it into the existing workflow. The most important changes include the addition of the `recreateRefToScoringManagerOutputs` function and its usage within the `recreateRefsInResults` function.
* [`src/services/ShSimulatorService.tsx`](diffhunk://#diff-2179512f339e13f570cb0371ad115ca927d2e7a48929797fd97671033ae6aa05R90-R100): Added the `recreateRefToScoringManagerOutputs` function to update the `scoringOutputJsonRef` property of each estimator with the corresponding output from the `ScoringManagerJSON`.
* [`src/services/ShSimulatorService.tsx`](diffhunk://#diff-2179512f339e13f570cb0371ad115ca927d2e7a48929797fd97671033ae6aa05L110-R129) …

Fix for missing filters

---

src/ThreeEditor/components/Dialog/LoadFileDialog.tsx

This pull request includes a small change to the `LoadFileDialog` component in the `src/ThreeEditor/components/Dialog/LoadFileDialog.tsx` file. The change adds `aria-label` attributes to the 'Cancel' and 'Clear and Proceed' buttons to improve accessibility.
Accessibility improvements:
* [`src/ThreeEditor/components/Dialog/LoadFileDialog.tsx`](diffhunk://#diff-93a5dd4d70deaec3dfb3a111218e58714d614842f5577d3cb7834f7c9c132920R45-R52): Added `aria-label='cancel'` to the 'Cancel' button and `aria-label='clear and proceed'` to the 'Clear and Proceed' button.

Add aria labels

---

public/examples/ex6.json
public/examples/ex7.json

This pull request includes updates to the `public/examples/ex6.json` and `public/examples/ex7.json` files to modify the `worldZone` properties. The most important changes involve enabling the `autoCalculate` feature and updating the geometry parameters and material UUID.
Changes to `worldZone` properties:
* Enabled `autoCalculate` by setting it to `true` in both `ex6.json` and `ex7.json`. [[1]](diffhunk://#diff-281a8e091a6ed75943ad9f2ed4301598a34fe04cce90b4bc1e5a0c1cea885dd3L373-R385) [[2]](diffhunk://#diff-af48780ad5a934c4fec2b562589e4788a423159b9506505817c0aa17299e5099L362-R374)
* Updated the `geometryData` parameters: `depth` to `13.200000000000001`, `height` to `11`, and `width` to `11` in both `ex6.json` and `ex7.json`. [[1]](diffhunk://#diff-281a8e091a6ed75943ad9f2ed4301598a34fe04cce …

Fixed example files

---

src/ThreeEditor/components/Dialog/RejectKeycloakRefreshUserDialog.tsx
src/services/AuthService.tsx
src/services/DialogService.tsx

Closes #1785
This PR refactors tokenVerification function in AuthService:
- extracts functions for user changin and parsing error messages coming from server
- adds null coalescence operator when using keycloak object to match type definitions

Present meaningful message to user when backend is unreachable

---

src/ThreeEditor/Simulation/CustomStoppingPower/CustomStoppingPower.ts
src/services/AuthService.tsx
src/util/keycloak/KeycloakProvider.tsx

The error overlay that appears on UI load is shown because of `Promise.reject()` or `throw` calls, which this PR removes.
- `Promise.reject()` in `AuthService` doesn't appear to serve any purpose so it's replaced with `resolve()`
- `throw error` in CustomStoppingPower is called when importing stopping file configs doesn't work - it is an implementation detail not to be shown to user, but I leave a `console.log()` to hopefully catch it
- `throw new Error(err)` in `KeycloakProvider` is never caught inside the component, so it is replaced with `console.log()`

Remove unnecessary and unhandled promise rejections

---

src/ThreeEditor/Simulation/CustomStoppingPower/CustomStoppingPower.ts
src/ThreeEditor/components/Sidebar/properties/category/ObjectMaterial.tsx

This pull request removes unnecessary `console.log` statements from the codebase to clean up debugging artifacts and improve code readability.
Code cleanup:
* [`src/ThreeEditor/Simulation/CustomStoppingPower/CustomStoppingPower.ts`](diffhunk://#diff-bcebd4d3da2e15dd65056e455f354a69d9951f3be79ed202522cef134fa38da0L55): Removed a `console.log` statement that logged the `zone` object during iteration over `editorJson.zoneManager.zones`.
* [`src/ThreeEditor/components/Sidebar/properties/category/ObjectMaterial.tsx`](diffhunk://#diff-228d3a246c7224c2fc0b42013a0d95cf511ab3df15cf6b17b7741e8698c5c515L194): Removed a `console.log` statement that logged the `watchedObject.object` during color input changes in the `ObjectMaterial` component.

unnecessary console log cleaning

---

.github/workflows/cleanup_closed_pr_packages.yaml
.github/workflows/manual_test.yml
.github/workflows/node.js.yml
.github/workflows/packages_retention.yaml
buildPython.js

This pull request includes updates to GitHub Actions workflows and a minor dependency version change in the `buildPython.js` file. The most important changes involve standardizing permissions across workflows, updating dependencies, and refining testing strategies.
* **Standardized permissions in workflows**:
- Added `contents: read` and `packages: write` permissions to `.github/workflows/cleanup_closed_pr_packages.yaml` and `.github/workflows/packages_retention.yaml`. These permissions are necessary for repository checkout and deleting packages from GHCR. [[1]](diffhunk://#diff-645a3e5794e0fa61371c18d674ddfe48dddc6fabbc84edd192ecaa65d04a3955R12-R14) [[2]](diffhunk://#diff-7c079a19bd0a85ecf3d8f82811baf9b539e2a46b51c49b81d7b6358a3c81bc9bR12-R14)
- Added `contents: read` permissions to …

build(workflow): update Node.js version to 22.x and adjust permissions

---

package-lock.json
package.json
src/JsRoot/GraphData.tsx
src/JsRoot/components/JsRootGraph1D.tsx
src/JsRoot/components/JsRootGraph2D.tsx
src/JsRoot/components/JsRootMultiGraph1D.tsx

This pull request includes updates to dependencies and introduces a new scaling factor for Y-axis visualization in graph components. The changes ensure better graph rendering and maintainability of the code.
* Updated the `jsroot` dependency in `package.json` from version `^7.8.2` to `^7.9.0` to include the latest features and fixes.
* Added a new constant `MAX_SCALING_FACTOR` in `src/JsRoot/GraphData.tsx` to define a scaling factor for the Y-axis, ensuring the maximum value is slightly larger than the actual maximum for better visualization.
* Updated `JsRootGraph1D` in `src/JsRoot/components/JsRootGraph1D.tsx` to use `MAX_SCALING_FACTOR` for setting the maximum value of the Y-axis, replacing hardcoded logic.
* Updated `JsRootMultiGraph1D` in …

upgrade to jsroot 7.9.0

---

public/examples/ex8.json
src/ThreeEditor/Simulation/Scoring/ScoringOutputTypes.ts
src/ThreeEditor/components/Sidebar/EditorSidebar.tsx
src/examples/exampleMap.json
src/types/RequestTypes.ts

This pull request introduces support for the Geant4 simulator in the application. The key changes include adding a new example project for Geant4, updating the simulator types and descriptions, and modifying the UI to accommodate Geant4-specific elements.
* **New Example Project**: Added a new Geant4 example project (`ex8.json`) to the `public/examples` directory. This project includes an empty Geant4 setup with metadata, managers, and a basic beam configuration.
* **Simulator Type Update**: Added `GEANT4` to the `SimulatorType` enum and updated the `SimulatorNames` map to include "Geant4".
* **Simulator Descriptions**: Updated `EditorSidebar` to include a description for Geant4-specific options.
* **Geometry and Scoring Tabs**: Added Geant4-specific placeholder elements to the geometry …

add geant4 selection

---

.github/workflows/manual_test.yml
.github/workflows/node.js.yml

This pull request updates the Node.js versions used in GitHub Actions workflows to include the latest version (24.x) for testing and compatibility purposes.
Workflow updates:
* [`.github/workflows/manual_test.yml`](diffhunk://#diff-cb08d37d26dd2d11ba4235a4aff4a4fb8c49779b0f9b5c3884531244d2566d5aL17-R17): Added Node.js version 24.x to the matrix of versions tested in the manual test workflow.
* [`.github/workflows/node.js.yml`](diffhunk://#diff-014228303dff9a1af15f4bbd18401f906380129b10ae2a2c62f8b8be592ff88eL21-R21): Added Node.js version 24.x to the matrix of versions tested in the Node.js workflow.

build: update Node.js version matrix to include 24.x

---

public/examples/ex8.json
src/ThreeEditor/Simulation/Figures/BasicFigures.ts
src/ThreeEditor/Simulation/Figures/FigureManager.ts

It seems that we didn't implement loading Geant4 figures from project JSON. Figures were saved with types from other simulators (CylinderFigure, BoxFigure, SphereFigure instead of Geant4Cylinder, Geant4Box, Geant4Sphere) and were rebuilt as though they were the former. This didn't fail on Geant4, but resulted in them not having material assigned.
Geant4 example has been updated accordintly, it should load the correct materials now.

Fix loading Geant4 figures from json
